markdown: rdiscount
permalink: /:categories/:year-:month/:title
url: http://i8g.org
name: i8g.org
author: freebug
email: cnfreebug@gamil.com
#duoshuo: ***多说评论帐号***
#cnzz: ***站长统计(可选)***
github: freebug
pygments: true
safe: true
paginate: 20
about: "这里是 freebug 的个人博客，创建于 2014 年。


exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
title : freebug's page
tagline: i8g, i freebug